// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAyXEwovUDqcovlzRTQfgsrfy3WxrG0ug',
    appId: '1:95069705430:web:26c0ab210ac646ff3aa577',
    messagingSenderId: '95069705430',
    projectId: 'e-commercedev-e9149',
    authDomain: 'e-commercedev-e9149.firebaseapp.com',
    storageBucket: 'e-commercedev-e9149.firebasestorage.app',
    measurementId: 'G-GT42D3M871',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVwOC-t-q62eEvDLRJRcE9t55wJpEBlkU',
    appId: '1:95069705430:android:89917b8ecadced9e3aa577',
    messagingSenderId: '95069705430',
    projectId: 'e-commercedev-e9149',
    storageBucket: 'e-commercedev-e9149.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjImgRSgwqEBBNz9uPn1gIywJAhyyk9rY',
    appId: '1:95069705430:ios:1ef4af34fc300bc43aa577',
    messagingSenderId: '95069705430',
    projectId: 'e-commercedev-e9149',
    storageBucket: 'e-commercedev-e9149.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjImgRSgwqEBBNz9uPn1gIywJAhyyk9rY',
    appId: '1:95069705430:ios:1ef4af34fc300bc43aa577',
    messagingSenderId: '95069705430',
    projectId: 'e-commercedev-e9149',
    storageBucket: 'e-commercedev-e9149.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );
}
